name: Windows

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-windows
  cancel-in-progress: true

jobs:
  WIN32-MSVC10:
    name: WIN32 MSVC@19.29 - MPI ${{matrix.mpi}} - AMReX ${{matrix.amrex_mode}}
    runs-on: windows-latest
    strategy:
      matrix:
        mpi: [OFF, ON]
        amrex_mode: [internal, external_src]

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Clone AMReX for dependency scripts
      run: |
        git clone https://github.com/AMReX-Codes/amrex.git ${{runner.workspace}}/amrex

    - name: Setup
      run: |
        if ("${{matrix.amrex_mode}}" -eq "external_src") {
          echo "AMREX_SRC_DIR=${{runner.workspace}}/amrex" >> $env:GITHUB_ENV
        }

    - name: Configure Project and Generate Build System
      run: |
        if ("${{matrix.amrex_mode}}" -eq "external_src") {
          cmake -S . -B build-${{matrix.mpi}}-${{matrix.amrex_mode}} `
            -DCMAKE_INSTALL_PREFIX:PATH=${{runner.workspace}}/FerroX/install `
            -DCMAKE_BUILD_TYPE:STRING=Debug `
            -DFerroX_MPI:BOOL=${{matrix.mpi}} `
            -DFerroX_ENABLE_ALL_WARNINGS:BOOL=OFF `
            -DFerroX_amrex_src:PATH=${{env.AMREX_SRC_DIR}} `
            ${{github.workspace}};
        } else {
          cmake -S . -B build-${{matrix.mpi}}-${{matrix.amrex_mode}} `
            -DCMAKE_INSTALL_PREFIX:PATH=${{runner.workspace}}/FerroX/install `
            -DCMAKE_BUILD_TYPE:STRING=Debug `
            -DFerroX_MPI:BOOL=${{matrix.mpi}} `
            -DFerroX_ENABLE_ALL_WARNINGS:BOOL=OFF `
            ${{github.workspace}};
        }

    - name: Compile and Link
      run: |
        cmake --build build-${{matrix.mpi}}-${{matrix.amrex_mode}} --parallel 2 --verbose

